In [1]:
import numpy as np


In [7]:
# list to numpy array
l=[]
a=np.array(l)
type(a)

numpy.ndarray

In [13]:
l=[3,8,True]
a=np.array(l)
print(type(a))
print(a.dtype) # it is giving datatype


<class 'numpy.ndarray'>
int64


In [19]:
a=np.array([[[[[1,4,6]]]]])
a.ndim # no of dimension

5

In [20]:
a=np.array([[[1,4,6,8,9,10]]])
a.size

6

In [21]:
a.dtype

dtype('int64')

In [24]:
a.shape

(1, 1, 6)

In [25]:
b=np.array([[1,2,3,6],[4,5,6,8],
            [7,8,9,10]])
print(b)
# check dim
print(b.ndim)
# type
print(b.dtype)
# shape
print(b.shape)
# size
print(b.size)

[[ 1  2  3  6]
 [ 4  5  6  8]
 [ 7  8  9 10]]
2
int64
(3, 4)
12


In [41]:
l=[1,2,3,4,5]
a=np.array(l)
a

array([1, 2, 3, 4, 5])

In [44]:
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) # list of lists
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [45]:
print('The Dimension of array',b.ndim)

The Dimension of array 2


In [46]:
print('The size of array:',b.size)

The size of array: 12


In [47]:
print('The datatype of element:',b.dtype)

The datatype of element: int64


In [48]:
print('The type of structure:',type(b))

The type of structure: <class 'numpy.ndarray'>


In [49]:
print('The shape:',b.shape)

The shape: (3, 4)


In [26]:
arr1= np.array([[[1,2,3],[4,5,6]], 
                [[7,8,9],[10,11,12]]])
arr1
#2 blocks

#each block has 2 rows

#each row has 3 columns

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [27]:
arr1.shape

(2, 2, 3)

In [2]:
my_matrix=[1,2,3,4,5],[6,7,8,9,10],
[11,12,13,14,15]
b=np.array(my_matrix)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [41]:
b[1,4:990000000]

array([10])

In [4]:
b[0,1:2]

array([2])

In [45]:
b
b # rows , col

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [43]:
b[0:2,1:]

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10]])

In [3]:
b[1:,0:2]

array([[6, 7]])

In [8]:
arr1= np.array([[[1,2,3],[4,5,6]],
                [[7,8,9],[10,11,12]]])
arr1
#arr1[0:1,::,0::2]
#arr1[0:1,::,0::2]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [60]:
arr1[1:]

array([[[ 7,  8,  9],
        [10, 11, 12]]])

In [9]:
arr1[1:,::,0::2]

array([[[ 7,  9],
        [10, 12]]])

In [10]:
arr1[0,::,1:]

array([[2, 3],
       [5, 6]])

In [29]:
arr1[1:,:,0:2]

array([[[ 7,  8],
        [10, 11]]])

In [30]:
arr1[1:]

array([[[ 7,  8,  9],
        [10, 11, 12]]])

In [83]:
a1=np.array([1,2,3,4,5,6,7,8,9,10,11,12,
            13,14,15,16,17,18
           ])
a2=a1.reshape(6,3)
a2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [86]:
a1.reshape(2,1,9)

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14, 15, 16, 17, 18]]])

In [87]:
a1.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [88]:
np.arange(2,20,5)

array([ 2,  7, 12, 17])

In [93]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [94]:
np.zeros([2,3,2])

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [95]:
np.ones([3,5,3])

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [39]:
np.zeros((5,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [102]:
np.eye(3,dtype=int) 

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [47]:
np.linspace(0,25, retstep=True) # 25-0/50-1

(array([ 0.        ,  0.51020408,  1.02040816,  1.53061224,  2.04081633,
         2.55102041,  3.06122449,  3.57142857,  4.08163265,  4.59183673,
         5.10204082,  5.6122449 ,  6.12244898,  6.63265306,  7.14285714,
         7.65306122,  8.16326531,  8.67346939,  9.18367347,  9.69387755,
        10.20408163, 10.71428571, 11.2244898 , 11.73469388, 12.24489796,
        12.75510204, 13.26530612, 13.7755102 , 14.28571429, 14.79591837,
        15.30612245, 15.81632653, 16.32653061, 16.83673469, 17.34693878,
        17.85714286, 18.36734694, 18.87755102, 19.3877551 , 19.89795918,
        20.40816327, 20.91836735, 21.42857143, 21.93877551, 22.44897959,
        22.95918367, 23.46938776, 23.97959184, 24.48979592, 25.        ]),
 np.float64(0.5102040816326531))

In [103]:
25/49

0.5102040816326531

In [107]:
1.88+4.88

6.76

In [50]:
np.linspace(3,20,10,retstep=False) #20-3/10-1=1.88

array([ 3.        ,  4.88888889,  6.77777778,  8.66666667, 10.55555556,
       12.44444444, 14.33333333, 16.22222222, 18.11111111, 20.        ])

In [51]:
np.linspace(3,20,10,retstep=True)

(array([ 3.        ,  4.88888889,  6.77777778,  8.66666667, 10.55555556,
        12.44444444, 14.33333333, 16.22222222, 18.11111111, 20.        ]),
 np.float64(1.8888888888888888))

In [109]:
np.linspace(3,10,2,retstep=True) # 10-3/2-1

(array([ 3., 10.]), np.float64(7.0))

In [21]:
np.random.rand(2)

array([0.95851709, 0.09688456])

In [76]:
np.random.randint(12)

0

In [79]:
arr1=np.random.randn(5)  # 50 observations from std normal distribution
arr1

array([ 0.8976881 , -1.06883852, -0.56187683, -0.98249845, -0.52357572])

In [81]:
np.mean(arr1)

np.float64(-0.44782028315345696)

In [80]:
np.median(arr1)

np.float64(-0.5618768344037836)

In [63]:
np.std(arr1)

np.float64(1.0887928767074344)

In [86]:
arr2=np.random.randint(1,100,20)

In [87]:
arr2

array([92, 57, 71, 81, 85, 97, 81, 40, 94, 70, 25, 20, 33, 36, 58, 28, 89,
       89, 57, 71], dtype=int32)

In [89]:
arr2.min()

np.int32(20)

In [90]:
arr2.argmax()

np.int64(5)

In [91]:
arr2.argmin()

np.int64(11)

In [93]:
arr=np.array([1,2,1010,4,108,18,71,610])
arr

array([   1,    2, 1010,    4,  108,   18,   71,  610])

In [94]:
arr[arr<100]

array([ 1,  2,  4, 18, 71])

In [98]:
arr2=np.array([False,True,False,False,True])

In [99]:
np.where(arr2)

(array([1, 4]),)

In [95]:
arr=np.array([1,2,1010,4,108,18,71,610])
arr

array([   1,    2, 1010,    4,  108,   18,   71,  610])

In [97]:
np.where(arr>601)

(array([2, 7]),)

In [101]:
a = np.arange(12).reshape(4,3)
b = np.arange(3)

print(a)
print(b)

print(a+b)
# 4,3 1,3
# 4,3 3,3

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [103]:
a = np.arange(12).reshape(3,4)
b = np.arange(3)

print(a)
print(b)

#print(a+b)
# (3,4 ) (1,3)
#(3,4) (3,3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2]


In [78]:
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)

print(a)
print(b)

print(a+b)
# (1,3) (3,1)
# (3,3) (3,3)

[[0 1 2]]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [104]:
a = np.arange(3).reshape(1,3)
b = np.arange(4).reshape(4,1)

print(a)
print(b)

print(a + b)
#(1,3) (4,1)
# (4,3) (4,3)

[[0 1 2]]
[[0]
 [1]
 [2]
 [3]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [106]:
a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(4,3)

print(a)
print(b)

#print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [108]:
a = np.arange(16).reshape(4,4)
b = np.arange(4).reshape(2,2)

print(a)
print(b)

#print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1]
 [2 3]]


In [109]:
a = np.array([1])
# shape -> (1,1)
b = np.arange(4).reshape(2,2)
# shape -> (2,2)

print(a)
print(b)

print(a+b)


[1]
[[0 1]
 [2 3]]
[[1 2]
 [3 4]]
